version: '3.9'
name: 'dev'
services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.dev/postgres.env
  api:
    build:
      context: ./apps/api
      dockerfile: ./Dockerfile
    container_name: api
    image: backend:api-v1.0.1
    env_file:
      - ./.envs/.dev/api.env
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deploy/nginx/ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - api

volumes:
  postgres_data: